controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    tricycle_controller:
      type: tricycle_steering_controller/TricycleSteeringController

tricycle_controller:
  ros__parameters:
    in_chained_mode: false
    reference_timeout: 1.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    wheelbase: 0.330
    wheel_track: 0.305
    front_wheels_radius: 0.070
    rear_wheels_radius: 0.075
    front_wheels_names: [front_wheel_joint]
    rear_wheels_names: [left_wheel_joint, right_wheel_joint]


    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]

