controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_steering_controller:
      type: steering_controllers_library/SteeringControllersLibrary

tricycle_steering_controller:
  ros__parameters:

    reference_timeout: 0.1
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    rear_wheels_names: [left_wheel_joint, right_wheel_joint]
    front_wheels_names: [front_wheel_joint]

    wheelbase: 0.330
    wheel_track: 0.305
    front_wheels_radius: 0.070
    rear_wheels_radius: 0.075